// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Golden1.Automation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Golden1 Global Navigation Validation")]
    public partial class Golden1GlobalNavigationValidationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Navigation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Golden1 Global Navigation Validation", "  As a user of the Golden1 website\r\n  I want to validate the navigation menu func" +
                    "tionality\r\n  So that I can access different sections of the website easily", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
  testRunner.Given("User is on Golden1 homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC_NAV_000 - Verify global navigation is visible")]
        [NUnit.Framework.CategoryAttribute("Navigation")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        [NUnit.Framework.CategoryAttribute("Critical")]
        public void TC_NAV_000_VerifyGlobalNavigationIsVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "Navigation",
                    "Smoke",
                    "Critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC_NAV_000 - Verify global navigation is visible", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 11
  testRunner.Then("Navigation should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Menu"});
                table1.AddRow(new string[] {
                            "Personal"});
                table1.AddRow(new string[] {
                            "Business"});
                table1.AddRow(new string[] {
                            "Financial Wellness"});
                table1.AddRow(new string[] {
                            "Appointments"});
                table1.AddRow(new string[] {
                            "Locations"});
                table1.AddRow(new string[] {
                            "Membership"});
                table1.AddRow(new string[] {
                            "Help Center"});
#line 12
  testRunner.And("The following menu options should be present in top navigation:", ((string)(null)), table1, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<TC_ID> - Validate navigation link functionality")]
        [NUnit.Framework.CategoryAttribute("Navigation")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("P1")]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_001", "Checking", "Free Checking", "free-checking-account", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_002", "Checking", "Easy Checking", "easy-checking-account", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_009", "Checking", "MarketRate Checking", "marketrate-checking-account", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_011", "Checking", "Premium Checking", "premium-checking-account", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_003", "Savings", "Money Market", "money-market-savings-account", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_004", "Home Loans", "Buy a Home", "home-loans/purchase", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_005", "Credit Cards", "Member Cash Rewards+ Card", "member-cash-rewards-plus", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_006", "Loans", "Personal Loans", "personal-loans", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_007", "Investing", "Make an Investment Plan", "investment-services", null)]
        [NUnit.Framework.TestCaseAttribute("TC_NAV_008", "Community", "Community Commitment", "our-commitment", null)]
        public void TC_ID_ValidateNavigationLinkFunctionality(string tC_ID, string mainMenu, string subMenu, string urlPart, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Navigation",
                    "Regression",
                    "P1"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TC_ID", tC_ID);
            argumentsOfScenario.Add("MainMenu", mainMenu);
            argumentsOfScenario.Add("SubMenu", subMenu);
            argumentsOfScenario.Add("UrlPart", urlPart);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("<TC_ID> - Validate navigation link functionality", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 24
  testRunner.When(string.Format("User navigates to \"{0}\" under \"{1}\"", subMenu, mainMenu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
  testRunner.Then(string.Format("User should be on \"{0}\" page", urlPart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC_NAV_010 - Verify main menu items are displayed")]
        [NUnit.Framework.CategoryAttribute("Navigation")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("P2")]
        public void TC_NAV_010_VerifyMainMenuItemsAreDisplayed()
        {
            string[] tagsOfScenario = new string[] {
                    "Navigation",
                    "Regression",
                    "P2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC_NAV_010 - Verify main menu items are displayed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Main Menu"});
                table2.AddRow(new string[] {
                            "Checking"});
                table2.AddRow(new string[] {
                            "Savings"});
                table2.AddRow(new string[] {
                            "Home Loans"});
                table2.AddRow(new string[] {
                            "Credit Cards"});
                table2.AddRow(new string[] {
                            "Loans"});
                table2.AddRow(new string[] {
                            "Investing"});
                table2.AddRow(new string[] {
                            "Community"});
#line 61
  testRunner.Then("The main menu should display the following items:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
